# Generated by Django 4.0.2 on 2022-03-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_likes_delete_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time']},
        ),
    ]
